### PR TITLE
fix some position problems

### LINKED ISSUE #78: Job configuration page layout and JS issue in Chrome
Here's how the page looks like here:

image

The error while trying to parse dates is:

> vue:6 TypeError: Cannot read property 'length' of null
>     at wn.eval (eval at Ya (vue:6), <anonymous>:3:3901)
>     at wn.e._render (vue:6)
>     at wn.r (vue:6)
>     at fn.get (vue:6)
>     at new fn (vue:6)
>     at vue:6
>     at wn.$mount (vue:6)
>     at wn.$mount (vue:6)
>     at wn.t._init (vue:6)
>     at new wn (vue:6)

### LINKED ISSUE #79: Layout issue on configuration page (button is outside of screen, if validation warning pops-up)
image

### PR DESCRIPTION
**Pull request by cocoon**
fix for:  Layout issue on configuration page (button is outside of screen, if validation warning pops-up) #79 
fix for:  Job configuration page layout and JS issue in Chrome #78 

fixes https://github.com/bamotav/Hangfire.RecurringJobAdmin/issues/78
fixes https://github.com/bamotav/Hangfire.RecurringJobAdmin/issues/79

### CODE REVIEW

**Review by LucasBLs — APPROVED** [review]

**Review by fulviomoya — APPROVED** [review]
Thanks @cocoon

**Review by bamotav — APPROVED** [review]
Excellent work.

**Comment by rinoab08** [comment]
how to get the updated repository in visual studio code. I'm already install from nuget hangfire recurring job in my project but version 1.0.5.

**Comment by rinoab08** [comment]
Screen Shot 2023-10-20 at 10 48 14
in my project still left - 296 in id app

**Pull request merged**
