### PR TITLE
Downgrade Newtonsoft.Json package version

### LINKED ISSUE #17: Is Newtonsoft.Json (>= 12.0.2) really required?!
I have a conflict between two libraries, this one require 
**Newtonsoft.Json (>= 12.0.2)**
and the other one
**Newtonsoft.Json (>= 10.0.0 && < 11.0.0)**
Since it require a DLL less than v11 may you please check if **Newtonsoft.Json >= 10.0.3** is ok.

### PR DESCRIPTION
**Pull request by Jadhielv**
### General
Downgrade Newtonsoft.Json package version to 11.0.1

- [x] Fix #17

@bamotav if you have time please take a look at this PR.

### CODE REVIEW

**Comment by Jadhielv** [comment]
@bamotav if you have time please take a look at this PR.

**Review by bamotav — COMMENTED** [review]
@Jadhielv I don't see the commit that removes the property that is never used.

**Review by bamotav — APPROVED** [review]
Excelente job @Jadhielv

**Comment by Jadhielv** [comment]
> 
> 
> @Jadhielv I don't see the commit that removes the property that is never used.
> 
> In this issue #42 :
> 
> image

Done @bamotav. Check this PR: #44

**Pull request merged**
